#!/usr/bin/env python3
"""Render the site footer (Snir's footer DEV package, 17.9.2026) and the pink booking strip into index.html, shop/index.html and shop/product.html,
between <!-- footer:start --> and <!-- footer:end --> (the first run replaces the old <footer> element).

One template, three pages: only the asset base path and the in-page link targets differ.
Contact and social links come from site.config.js at runtime (data-config / data-booking / data-waze / data-link):
a value left null keeps the tile as designed but inert. TikTok is display only ("בקרוב") until the account exists.

usage: python3 tools/sync_footer.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSTAGRAM = "https://www.instagram.com/padelclub.azor/"
WAZE = "https://waze.com/ul?q=%D7%96%27%D7%91%D7%95%D7%98%D7%99%D7%A0%D7%A1%D7%A7%D7%99%2028%20%D7%90%D7%96%D7%95%D7%A8&navigate=yes"
BOOKING = "https://www.lazuz.co.il/"

PAGES = {
    "index.html": {"base": "", "home": "#top", "home_label": "לראש העמוד", "anchor": "#", "shop": "#shop"},
    "shop/index.html": {"base": "../", "home": "../", "home_label": "לעמוד הבית", "anchor": "../#", "shop": "./"},
    "shop/product.html": {"base": "../", "home": "../", "home_label": "לעמוד הבית", "anchor": "../#", "shop": "./"},
}

def icon(name, cls="footer-icon"):
    svg = (ROOT / f"assets/icons/{name}.svg").read_text(encoding="utf-8").strip()
    svg = svg.replace('xmlns="http://www.w3.org/2000/svg" ', "")
    svg = re.sub(r"\s*\n\s*", "", svg)
    return svg.replace("<svg ", f'<svg class="{cls}" aria-hidden="true" focusable="false" ', 1)

def footer(p):
    b, a = p["base"], p["anchor"]
    chevron = icon("chevron-left", "footer-cta-icon")
    nav = [("בית", p["home"]), ("מגרשים", f"{a}courts"), ("אירועים", f"{a}tournaments"),
           ("חנות", p["shop"]), ("אודות", f"{a}about"), ("צור קשר", "#site-footer")]
    nav_html = "\n".join(f'          <li><a href="{href}">{label}</a></li>' for label, href in nav)
    return f'''<!-- footer:start / generated by tools/sync_footer.py, do not edit by hand -->
<footer class="site-footer on-dark" id="site-footer">
  <div class="footer-hero">
    <img class="footer-bg" src="{b}assets/footer/footer-bg.webp" srcset="{b}assets/footer/footer-bg-836.webp 836w, {b}assets/footer/footer-bg.webp 1672w"
         sizes="100vw" width="1672" height="405" alt="" loading="lazy" decoding="async">
    <div class="footer-hero-inner">
      <div class="footer-hero-copy">
        <h2 class="footer-title">הצטרפו לקהילת <span class="footer-title-accent">הפאדל של אזור</span></h2>
        <p class="footer-sub">מגרשים, אנשים טובים ואווירה שמחברת.</p>
        <div class="footer-actions">
          <a class="btn footer-cta footer-cta--primary" href="{BOOKING}" target="_blank" rel="noopener" data-booking>הזמנת מגרש{chevron}</a>
          <!-- "דברו איתנו": site.config.js → links.contact (WhatsApp or phone once supplied) -->
          <a class="btn footer-cta footer-cta--ghost" data-link="contact">דברו איתנו{chevron}</a>
        </div>
      </div>
      <div class="footer-brand-block">
        <p class="footer-brand-line">יותר<br>מפאדל.<br>זו קהילה.</p>
        <a class="footer-brand" href="{p["home"]}" aria-label="The Padel Club, {p["home_label"]}">
          <img src="{b}assets/brand/logo-outline-240.webp" srcset="{b}assets/brand/logo-outline-240.webp 1x, {b}assets/brand/logo-outline-480.webp 2x"
               width="240" height="240" alt="The Padel Club" loading="lazy" decoding="async">
        </a>
      </div>
    </div>
  </div>

  <div class="footer-inner">
    <!-- contact and social: phone, WhatsApp and Facebook read site.config.js (phone / whatsappUrl / facebookUrl), inert while null -->
    <ul class="footer-contacts">
      <li><a class="footer-contact" href="{WAZE}" target="_blank" rel="noopener" data-waze>{icon("map-pin")}<b>ז׳בוטינסקי 28, אזור</b><span>נשמח לראות אתכם</span></a></li>
      <li><a class="footer-contact" data-config="phone">{icon("phone")}<b>טלפון</b><span>דברו איתנו</span></a></li>
      <li><a class="footer-contact" data-config="whatsappUrl">{icon("whatsapp")}<b>וואטסאפ</b><span>דברו איתנו</span></a></li>
      <li><a class="footer-contact" href="{INSTAGRAM}" target="_blank" rel="noopener" data-config="instagramUrl">{icon("instagram")}<b>אינסטגרם</b><span>עקבו אחרינו</span></a></li>
      <li><a class="footer-contact" data-config="facebookUrl">{icon("facebook")}<b>פייסבוק</b><span>עקבו אחרינו</span></a></li>
      <!-- TikTok: future placeholder, display only, not a link yet -->
      <li><span class="footer-contact is-soon">{icon("tiktok")}<b>טיקטוק</b><span>בקרוב</span></span></li>
    </ul>

    <div class="footer-bottom">
      <p class="footer-legal"><span class="latin" dir="ltr" lang="en">© <span id="year">2026</span> The Padel Club Azor.</span> <span>כל הזכויות שמורות.</span></p>
      <nav class="footer-nav" aria-label="ניווט תחתון">
        <ul>
{nav_html}
        </ul>
      </nav>
      <p class="footer-tagline" dir="ltr" lang="en">WELLNESS &amp; SOCIAL</p>
    </div>
  </div>
</footer>

<!-- booking strip: pink, fixed to the bottom of the screen on every page, always visible (Snir, 17.9.2026) -->
<a class="book-strip" href="{BOOKING}" target="_blank" rel="noopener" data-booking><span>הזמן מגרש עכשיו</span>{icon("chevron-left", "book-strip-icon")}</a>
<!-- footer:end -->'''

for rel, p in PAGES.items():
    path = ROOT / rel
    page = path.read_text(encoding="utf-8")
    block = footer(p)
    if "<!-- footer:start" in page:
        page, n = re.subn(r"<!-- footer:start.*?<!-- footer:end -->", lambda m: block, page, flags=re.S)
    else:
        page, n = re.subn(r'<footer class="site-footer[^"]*">.*?</footer>', lambda m: block, page, flags=re.S)
    if n != 1:
        raise SystemExit(f"{rel}: footer block not found exactly once")
    path.write_text(page, encoding="utf-8")
    print(f"footer rendered into {rel}")
